- name: Deploy WAR to Apache Tomcat 
  hosts: app_server
  become: yes

  vars:
    tomcat_major: "9"
    tomcat_version: "9.0.87"
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    tomcat_install_dir: "/opt/tomcat"
    nexus_war_url: "http://16.16.187.133:8081/repository/dobretech-re/com/example/myapp/1.0/myapp-1.0.war"
    war_file_name: "myapp-1.0.war"

  tasks:
    - name: Ensure required apt packages are installed
      apt:
        name:
          - openjdk-11-jdk
          - curl
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        create_home: no
        system: yes

    - name: Download and extract Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_major }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /tmp/tomcat.tar.gz
        mode: '0644'

    - name: Create Tomcat installation directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes

    - name: Create symlink to Tomcat version directory
      file:
        src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_install_dir }}/latest"
        state: link
        force: yes

    - name: Ensure webapps directory exists
      file:
        path: "{{ tomcat_install_dir }}/latest/webapps"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0755'

    - name: Download WAR file from Nexus
      get_url:
        url: "{{ nexus_war_url }}"
        dest: "{{ tomcat_install_dir }}/latest/webapps/{{ war_file_name }}"
        mode: '0644'
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
      tags: deploy

    - name: Start Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: started
      tags: deploy

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reexec
