---
- name: Deploy WAR to Apache Tomcat
  hosts: app1
  become: yes

  vars:
    tomcat_version: 11.0.6
    tomcat_download_url: https://downloads.apache.org/tomcat/tomcat-11/v11.0.6/bin/apache-tomcat-11.0.6-deployer.tar.gz
    tomcat_install_dir: /opt/tomcat
    war_file_path: war_file_path: /var/lib/jenkins/workspace/DevOps/target/myapp.war

  tasks:
    - name: Install required packages
      apt:
        name: default-jdk
        state: present
        update_cache: yes
      tags: deploy

    - name: Create Tomcat group
      group:
        name: tomcat
      tags: deploy

    - name: Create Tomcat user
      user:
        name: tomcat
        group: tomcat
        home: "{{ tomcat_install_dir }}"
        shell: /bin/false
        system: yes
      tags: deploy

    - name: Ensure Tomcat install directory exists
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'
      tags: deploy

    - name: Download and extract Tomcat
      unarchive:
        src: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
      tags: deploy

    - name: Deploy WAR file to Tomcat webapps directory
      copy:
        src: "{{ war_file_path }}"
        dest: "{{ tomcat_install_dir }}/webapps/maven-web-pro1.war"
        owner: tomcat
        group: tomcat
        mode: '0644'
      tags: deploy

    - name: Ensure execute permissions on Tomcat scripts
      file:
        path: "{{ tomcat_install_dir }}/bin"
        recurse: yes
        mode: '0755'
      tags: deploy

    - name: Start Tomcat
      shell: "{{ tomcat_install_dir }}/bin/startup.sh"
      args:
        chdir: "{{ tomcat_install_dir }}/bin"
      tags: deploy
