---
- name: Deploy WAR to Apache Tomcat
  hosts: app1
  become: yes

  vars:
    tomcat_version: 11.0.6
    tomcat_user: tomcat
    tomcat_group: tomcat
    install_dir: /opt/tomcat
    java_home: /usr/lib/jvm/java-17-openjdk-amd64

  tasks:

    - name: Install required packages
      apt:
        name:
          - openjdk-17-jdk
          - curl
          - unzip
        state: present
        update_cache: yes

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        create_home: no
        system: yes

    - name: Ensure Tomcat install directory exists
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Download and extract Tomcat
      unarchive:
        src: "https://downloads.apache.org/tomcat/tomcat-11/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ install_dir }}"
        remote_src: yes
        creates: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Symlink to latest Tomcat
      file:
        src: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ install_dir }}/latest"
        state: link
        force: yes

    - name: Change ownership of Tomcat directory
      file:
        path: "{{ install_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Ensure Tomcat systemd service file exists
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking
          Environment=JAVA_HOME={{ java_home }}
          Environment=CATALINA_PID={{ install_dir }}/latest/temp/tomcat.pid
          Environment=CATALINA_HOME={{ install_dir }}/latest
          Environment=CATALINA_BASE={{ install_dir }}/latest
          ExecStart={{ install_dir }}/latest/bin/startup.sh
          ExecStop={{ install_dir }}/latest/bin/shutdown.sh
          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Ensure Tomcat is started and enabled
      systemd:
        name: tomcat
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
