- name: Deploy WAR to Apache Tomcat 
  hosts: app_server
  become: yes

  vars:
    tomcat_major: "9"
    tomcat_version: "9.0.87"
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    tomcat_install_dir: "/opt/tomcat"
    tomcat_url: "https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_major }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    nexus_war_url: "http://18.234.234.170:8081/repository/dobretech-fe/com/example/myapp/1.0/myapp-1.0.war"
    war_file_name: "myapp-1.0.war"

  tasks:
    - name: Ensure required apt packages are installed
      apt:
        name:
          - openjdk-11-jdk
          - curl
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        create_home: no
        system: yes

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: /tmp/tomcat.tar.gz
        mode: '0644'

    - name: Create Tomcat installation directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        creates: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Set correct permissions
      file:
        path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Create symlink to Tomcat
      file:
        src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_install_dir }}/latest"
        state: link
        force: yes

    - name: Download WAR file from Nexus
      get_url:
        url: "{{ nexus_war_url }}"
        dest: "{{ tomcat_install_dir }}/latest/webapps/{{ war_file_name }}"
        mode: '0644'
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
      tags: deploy

    - name: Create Tomcat systemd service
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User={{ tomcat_user }}
          Group={{ tomcat_group }}

          Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
          Environment="CATALINA_PID={{ tomcat_install_dir }}/latest/temp/tomcat.pid"
          Environment="CATALINA_HOME={{ tomcat_install_dir }}/latest"
          Environment="CATALINA_BASE={{ tomcat_install_dir }}/latest"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

          ExecStart={{ tomcat_install_dir }}/latest/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/latest/bin/shutdown.sh

          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd

    - name: Ensure Tomcat is started and enabled
      systemd:
        name: tomcat
        enabled: yes
        state: started
      tags: deploy

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reexec
