---
- name: Deploy WAR to Apache Tomcat
  hosts: app1
  become: yes
  vars:
    tomcat_version: 11.0.6
    tomcat_download_url: "https://downloads.apache.org/tomcat/tomcat-11/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}-deployer.tar.gz"
    tomcat_install_dir: /opt/tomcat
    war_file_url: "http://18.234.234.170:8081/repository/dobretech-re/com/example/myapp/1.0/myapp-1.0.war"
    war_file_name: myapp.war

  tasks:
    - name: Install required packages
      apt:
        name: default-jdk
        state: present
        update_cache: yes

    - name: Create Tomcat group
      group:
        name: tomcat

    - name: Create Tomcat user
      user:
        name: tomcat
        group: tomcat
        home: "{{ tomcat_install_dir }}"
        shell: /bin/false
        system: yes

    - name: Ensure Tomcat install directory exists
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: /tmp/apache-tomcat.tar.gz

    - name: Extract Tomcat archive
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set permissions
      file:
        path: "{{ tomcat_install_dir }}"
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Deploy WAR file
      get_url:
        url: "{{ war_file_url }}"
        dest: "{{ tomcat_install_dir }}/webapps/{{ war_file_name }}"
        mode: '0644'

    - name: Set JAVA_HOME for Tomcat
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
        create: yes
        state: present

    - name: Reload environment
      shell: source /etc/environment
      args:
        executable: /bin/bash

    - name: Start Tomcat
      shell: "{{ tomcat_install_dir }}/bin/startup.sh"
      become_user: tomcat
