---
- name: Deploy WAR to Apache Tomcat
  hosts: app1
  become: yes
  vars:
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_install_dir: /opt/tomcat
    tomcat_version: 9.0.82
    war_url: http://16.16.187.133:8081/repository/dobretech-re/com/example/myapp/1.0/myapp-1.0.war
    war_dest: /opt/tomcat/latest/webapps/myapp-1.0.war

  tasks:
    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present
      tags: deploy

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        create_home: no
        system: yes
      tags: deploy

    - name: Ensure Tomcat install directory exists
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      tags: deploy

    - name: Download and extract Tomcat
      unarchive:
        src: "https://archive.apache.org/dist/tomcat/tomcat-11/v11.0.6/bin/apache-tomcat-11.0.6.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
      when: not (tomcat_install_dir + '/bin/catalina.sh') is exists
      tags: deploy

    - name: Change ownership of Tomcat directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
      tags: deploy

    - name: Ensure Tomcat service file exists
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          Environment=JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          Environment=CATALINA_PID={{ tomcat_install_dir }}/temp/tomcat.pid
          Environment=CATALINA_HOME={{ tomcat_install_dir }}
          Environment=CATALINA_BASE={{ tomcat_install_dir }}
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

          ExecStart={{ tomcat_install_dir }}/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/bin/shutdown.sh

          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
      tags: deploy

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      tags: deploy

    - name: Ensure Tomcat is started and enabled
      systemd:
        name: tomcat
        enabled: yes
        state: started
      tags: deploy

    - name: Ensure webapps directory exists
      file:
        path: "{{ tomcat_install_dir }}/webapps"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0755'
      tags: deploy

    - name: Download WAR file from Nexus
      get_url:
        url: "{{ war_url }}"
        dest: "{{ war_dest }}"
        mode: '0644'
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
      tags: deploy

    - name: Restart Tomcat to deploy WAR
      systemd:
        name: tomcat
        state: restarted
      tags: deploy
